ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("frontend.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from .views import HomeView, CartView, ProductView, CheckoutView, login_view, cart_query_view

app_name = "frontend"

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path("cart/", CartView.as_view(), name='cart'),
    path("product/", ProductView.as_view(), name='product'),
    path("checkout/", CheckoutView.as_view(), name='checkout'),
    path("login/", login_view, name="login"),
    path("cart-query/", cart_query_view, name="cart_query")

]

frontend/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_single_data(self):
        return self.product_set.last()


class Product(models.Model):
    name = models.CharField(max_length=50)
    label = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    price = models.DecimalField(decimal_places=2, max_digits=1000)
    discount = models.DecimalField(decimal_places=2, default=0, max_digits=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_discount_price(self):
        return round(self.price - ((self.discount/100)*self.price), 2)

    def get_single_image(self):
        if self.image_set.count() != 0:
            print(self.image_set.count)
            return self.image_set.first().name.url
        return ''

    def get_multiple_image(self):
        r = 3
        if self.image_set.count() != 0:
            return [image.name.url for image in self.image_set.all()[:r]]
        return ['']*r

    def get_all_image(self):
        if self.image_set.count() != 0:
            return [image.name.url for image in self.image_set.all()]
        return ['']



class Image(models.Model):
    name = models.ImageField(upload_to="images/")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} ({self.name})"

    def get_image_url(self):
        return self.name.url


class Information(models.Model):
    text = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_modified = models.DateTimeField(auto_now=True)
    is_purchased = models.BooleanField(default=False)

    def get_total_price(self):
        return sum([p.get_sumed_price() for p in self.cartitem_set.all()])

    def is_empty(self):
        return False if self.cartitem_set.count else True
    
    def get_all_items(self):
        return self.cartitem_set.all()
    
    def get_item_count(self):
        return self.cartitem_set.count()

    def __str__(self):
        return f"{self.user.username} (cart {self.id})"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_sumed_price(self):
        return self.product.get_discount_price() * self.quantity
    
    def __str__(self):
        return f"Cart[{self.cart.id}] ({self.cart.user.username})"

frontend/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={
            "class": "form-control form-control-lg login-email",
            "placeholder": "username"
        }
    ))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(
        attrs={
            "class": "form-control form-control-lg login-password",
            "placeholder": "8+ characters required"
        }
    ))

    class Meta:
        model = User
        fields = ["username", "password"]

frontend/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.views import View
from django.contrib.auth import login, authenticate
from .models import Product, Category
from .forms import LoginForm


class HomeView(View):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        carousel = list(products)[-1:-4:-1]
        categories = Category.objects.all()
        login_form = LoginForm()

        context = {
            "carousel": carousel,
            "products": products,
            "categories": categories,
            "login_form": login_form
        }
        return render(request, "frontend/home_page.html", context)


def login_view(request):
    if request.method == 'POST':
        print(request.POST['username'])
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,
                            username=username,
                            password=password
                            )
        if user is not None:
            login(request, user)
            return JsonResponse({"status": "ok"})
        else:
            return JsonResponse({"status": "bad"})


def cart_query_view(request):
    if request.method == 'POST':
        data = request.POST
        query = data.get('q')
        p_id = data.get('p')

        if query == "empty_cart":
            user_cart = request.user.cart_set.last()
            print(user_cart.cartitem_set.count())
            if user_cart.cartitem_set.count() == 0:
                return JsonResponse({"status": True})
            else:
                return JsonResponse({"status": False})
        if p_id and query == "in_cart":
            user_cart = request.user.cart_set.last()
            cartitem = user_cart.cartitem_set.filter(product_id=p_id)
            if cartitem:
                cartitem.delete()
                return JsonResponse({"status": False})
            else:
                product = Product.objects.filter(id=p_id).first()
                if product:
                    user_cart.cartitem_set.create(product=product)
                    return JsonResponse({"status": True})
        return JsonResponse({"status": None})


class CartView(View):
    def get(self, request):
        cart = request.user.cart_set.last()
        context = {
            "cart": cart
        }
        return render(request, "frontend/cart_page.html", context)


class CheckoutView(View):
    def get(self, request):
        cart = request.user.cart_set.last()
        context = {
            "cart": cart
        }
        return render(request, "frontend/checkout_page.html", context)


class ProductView(View):
    def get(self, request):
        products = Product.objects.all()
        context = {
            "products": products
        }
        return render(request, "frontend/product_page.html", context)

frontend/templates/frontend/home_page.html
{% extends "frontend/base.html" %}
{% load static %}
{% load frontend_extras %}

{% block content %}
<main id="content" role="main">
    <!-- Hero -->
    <div class="position-relative">
        <!-- Swiper Main Slider -->
        <div
            class="js-swiper-shop-classic-hero swiper bg-light swiper-initialized swiper-horizontal swiper-pointer-events">

            <div class="swiper-wrapper" id="swiper-wrapper-c02656619c616b45">
                {% for obj in carousel %}
                <!-- Slide -->
                <div class="swiper-slide">
                    <!-- Container -->
                    <div class="container content-space-t-2 content-space-b-3">
                        <div class="row align-items-lg-center">
                            <div class="col-lg-5 order-lg-2 mb-7 mb-lg-0">
                                <div class="mb-6">
                                    <h1 class="display-4 mb-4">{{ obj.name }}</h1>
                                    <p>{{ obj.label }}</p>
                                </div>

                                <div class="d-flex gap-2">    
                                        <a class="btn btn-primary rounded-pill" href="{% url 'frontend:cart' %}" pId="{{ obj.id }}" >${{ obj.get_discount_price }} - Buy!</a>
                                    <a class="btn btn-outline-primary btn-icon rounded-circle" href="#"
                                        data-bs-toggle="tooltip" data-bs-placement="top" title=""
                                        data-bs-original-title="Save for later">
                                        <i class="bi-heart-fill"></i>
                                    </a>
                                </div>
                            </div>
                            <!-- End Col -->

                            <div class="col-lg-6 order-lg-1">
                                <div class="w-75 mx-auto">
                                    <img class="img-fluid" src="{{ obj.get_single_image }}" alt="Image Description">
                                </div>
                            </div>
                            <!-- End Col -->
                        </div>
                        <!-- End Row -->
                    </div>
                    <!-- End Container -->
                </div>
                <!-- End Slide -->
                {% endfor %}

            </div>

            <!-- Swiper Thumbs Slider -->
            <div class="position-absolute bottom-0 start-0 end-0 mb-3">
                <div
                    class="js-swiper-shop-hero-thumbs swiper swiper-initialized swiper-horizontal swiper-pointer-events swiper-thumbs">
                    <div class="swiper-wrapper" id="swiper-wrapper-94cdc8d068319ffc" aria-live="polite"
                        style="flex-flow: row nowrap; justify-content: center;">
                        {% for obj in carousel %}
                        <!-- Slide -->
                        <div class="swiper-slide" role="group"
                            aria-label="{{ forloop.counter }} / {{ products.length }}"
                            style="max-width: fit-content; margin-right: 15px;">
                            <a class="js-swiper-thumb-progress swiper-thumb-progress-avatar" href="javascript:;"
                                tabindex="0">
                                <img class="swiper-thumb-progress-avatar-img" src="{{ obj.get_single_image }}"
                                    alt="Image Description">
                                <span class="swiper-thumb-progress"><svg version="1.1" viewBox="0 0 160 160">
                                        <path class="swiper-thumb-progress-path"
                                            d="M 79.98452083651917 4.000001576345426 A 76 76 0 1 1 79.89443752470656 4.0000733121155605 Z">
                                        </path>
                                    </svg></span></a>
                        </div>
                        <!-- End Slide -->
                        {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Arrows -->
            <div class="js-swiper-shop-classic-hero-button-next swiper-button-next" role="button"
                aria-label="Next slide" aria-controls="swiper-wrapper-c02656619c616b45"></div>
            <div class="js-swiper-shop-classic-hero-button-prev swiper-button-prev" role="button"
                aria-label="Previous slide" aria-controls="swiper-wrapper-c02656619c616b45"></div>
            <!-- End Swiper Main Slider -->
        </div>
        <!-- End Swiper Thumbs Slider -->
    </div>
    <!-- End Hero -->

    <!-- Icon Blocks -->
    {% include "frontend/widgets/intro.html" %}
    <!-- End Icon Blocks -->

    <!-- Card Grid -->
    <div class="container content-space-2 content-space-lg-3" style="margin-bottom: 0!important;">
        <!-- Heading -->
        <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
            <h2>The better way to shop with Vang top-products</h2>
        </div>
        <!-- End Heading -->

        <div class="row mb-2">
            {% for obj in categories %}
            {% if obj.get_single_data %}
            <div class="col-sm-6 col-md-4 mb-4">
                <!-- Card -->
                <div class="card card-bordered shadow-none overflow-hidden">
                    <div class="card-body d-flex align-items-center border-bottom p-0">
                        <div class="w-65">
                            <img class="img-fluid p-2" src="{{ obj.get_single_data.get_multiple_image.0 }}"
                                alt="Image Description">
                        </div>
                        <div class="w-35 border-start">
                            <div class="border-bottom">
                                <img class="img-fluid" src="{{ obj.get_single_data.get_multiple_image.1 }}"
                                    alt="Image Description">
                            </div>
                            <img class="img-fluid" src="{{ obj.get_single_data.get_multiple_image.2 }}"
                                alt="Image Description">
                        </div>
                    </div>

                    <div class="card-footer text-center">
                        <h3 class="card-title">{{ obj.name }}</h3>
                        <p class="card-text text-muted small">Starting from ${{ obj.get_single_data.get_discount_price }}</p>
                        <a class="btn btn-outline-primary btn-sm btn-transition rounded-pill px-6" href="#">View all</a>
                    </div>
                </div>
                <!-- End Card -->
            </div>
            <!-- End Col -->
            {% endif %}
            {% endfor %}

        </div>
        <!-- End Row -->

    </div>
    <!-- End Card Grid -->

    <!-- Card Grid -->
    <div class="container content-space-2 content-space-lg-3">
        <!-- Title -->
        <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
            <h2>What's trending</h2>
        </div>
        <!-- End Title -->

        <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mb-3">
            {% for obj in products %}
            <div class="col mb-4">
                <!-- Card -->
                <div class="card card-bordered shadow-none text-center h-100">
                    <div class="card-pinned">
                        <img class="card-img-top p-5" src="{{ obj.get_single_image }}" alt="Image Description">

                        <div class="card-pinned-top-start">
                            <span class="badge bg-success rounded-pill">New arrival</span>
                        </div>

                        <div class="card-pinned-top-end">
                            <button type="button" class="btn btn-outline-secondary btn-xs btn-icon rounded-circle"
                                data-bs-toggle="tooltip" data-bs-placement="top" title=""
                                data-bs-original-title="Save for later">
                                <i class="bi-heart"></i>
                            </button>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="mb-1">
                            <a class="link-sm link-secondary" href="#">{{ obj.category.name }}</a>
                        </div>
                        <a class="text-body" href="">{{ obj.name }}</a>
                        <p class="card-text text-dark">${{ obj.get_discount_price }} <span
                                class="text-body ms-1"><del>${{ obj.price }}</del></span></p>
                    </div>

                    <div class="card-footer d-flex flex-column align-items-center pt-0">
                        <!-- Rating -->
                        <a class="d-inline-flex align-items-center mb-3" href="#">
                            <div class="d-inline-flex gap-1 me-2">
                                <img src="{% static 'frontend/images/star-muted.svg' %}" alt="Review rating" width="16">
                                <img src="{% static 'frontend/images/star-muted.svg' %}" alt="Review rating" width="16">
                                <img src="{% static 'frontend/images/star-muted.svg' %}" alt="Review rating" width="16">
                                <img src="{% static 'frontend/images/star-muted.svg' %}" alt="Review rating" width="16">
                                <img src="{% static 'frontend/images/star-muted.svg' %}" alt="Review rating" width="16">
                            </div>
                            <span class="small">0</span>
                        </a>
                        <!-- End Rating -->
                        {% if user.is_authenticated %}
                            {% product_in_user_cart obj.id as in_cart %}
                            {% if in_cart %}
                            <button type="button" class="btn btn-primary btn-sm rounded-pill cart_query" onclick="addToCart(this)" pId="{{ obj.id }}">Added to cart!</button>
                            {% else %}
                            <button type="button" class="btn btn-outline-primary btn-sm rounded-pill cart_query" onclick="addToCart(this)" pId="{{ obj.id }}">Add to cart</button>
                            {% endif %}
                        {% else %}
                        <button type="button" class="btn btn-outline-primary btn-sm rounded-pill cart_query" onclick="" pId="{{ obj.id }}">Add to cart</button>
                        {% endif %}
                        
                    </div>
                </div>
                <!-- End Card -->
            </div>
            <!-- End Col -->
            {% endfor %}

        </div>
        <!-- End Row -->

        <div class="text-center">
            <a class="btn btn-outline-primary btn-transition rounded-pill" href="{% url 'frontend:product' %}">View all products</a>
        </div>
    </div>
    <!-- End Card Grid -->

</main>

{% endblock content %}

frontend/templates/frontend/widgets/cart.html
{% load static %}

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbarEmptyShoppingCart">
    <div class="offcanvas-header justify-content-end border-0 pb-0">
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">
      <div class="text-center">
        <div class="mb-5">
          <img class="avatar avatar-xl avatar-4x3"
            src="{% static 'frontend/images/oc-empty-cart.svg' %}" alt="SVG">
        </div>

        <div class="mb-5">
          <h3>Your cart is currently empty</h3>
          <p>Before proceed to checkout you must add some products to your shopping cart. You will find a lot of
            interesting products on our "Shop" page.</p>
        </div>

        <a class="btn btn-primary btn-transition rounded-pill px-6"
          href="{% url 'frontend:home' %}">Start shopping</a>
      </div>
    </div>
  </div>

frontend/templates/frontend/widgets/clients.html
{% load static %}

<div class="container content-space-2">
    <div class="row">
        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/hollister-dark.svg' %}"
                alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/levis-dark.svg' %}" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/new-balance-dark.svg' %}"
                alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/puma-dark.svg' %}" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/nike-dark.svg' %}" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="{% static 'frontend/images/tnf-dark.svg' %}" alt="Logo">
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>

frontend/templates/frontend/widgets/header.html
{% load static %}

<header id="header" class="navbar navbar-expand-lg navbar-end navbar-light">
    <div class="container">
      <nav class="js-mega-menu navbar-nav-wrap hs-menu-initialized hs-menu-horizontal">
        <!-- Default Logo -->
        <a class="navbar-brand" href="" aria-label="Front">
          <img class="navbar-brand-logo" src="{% static 'frontend/images/logo.svg' %}"
            alt="Logo">
        </a>
        <!-- End Default Logo -->

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-default">
            <i class="bi-list"></i>
          </span>
          <span class="navbar-toggler-toggled">
            <i class="bi-x"></i>
          </span>
        </button>
        <!-- End Toggler -->

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'frontend:home' %}">Home</a>
            </li>

            <li class="hs-has-sub-menu nav-item">
              {# a class="active" #}
              <a id="listingsDropdown" class="hs-mega-menu-invoker nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
              <div class="hs-sub-menu dropdown-menu hs-sub-menu-desktop-lg animated" aria-labelledby="listingsDropdown" style="min-width: 14rem; animation-duration: 300ms; display: none;">
                <a class="dropdown-item " href="#">Caps</a>
                <a class="dropdown-item " href="#">Tech</a>
              </div>
            </li>

            <li class="nav-item">
              <a class="nav-link " href="{% url 'frontend:product' %}">Products</a>
            </li>

            <!-- Pages -->
            <li class="hs-has-mega-menu nav-item" data-hs-mega-menu-item-options="{
                  &quot;desktop&quot;: {
                    &quot;position&quot;: &quot;right&quot;,
                    &quot;maxWidth&quot;: &quot;27rem&quot;
                  }
                }">
              <a id="pagesMegaMenu" class="hs-mega-menu-invoker nav-link dropdown-toggle " aria-current="page"
                href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">Promo</a>

              <!-- Mega Menu -->
              <div class="hs-mega-menu dropdown-menu hs-mega-menu-desktop-lg hs-position-right animated"
                aria-labelledby="pagesMegaMenu" style="min-width: 27rem; max-width: 27rem; animation-duration: 300ms;">

                <!-- Mega Menu Banner -->
                <div class="navbar-dropdown-menu-shop-banner">
                  <div class="d-flex">
                    <div class="flex-shrink-0">
                      <img class="navbar-dropdown-menu-shop-banner-img"
                        src="{% static 'frontend/images/img4.png' %}" alt="Image Description">
                    </div>

                    <div class="flex-grow-1 p-4">
                      <span class="h4 d-block text-primary">Win T-Shirt</span>
                      <p>Win one of our Front brand T-shirts.</p>
                      <a class="btn btn-sm btn-soft-primary btn-transition"
                        href="">Learn more <i
                          class="bi-chevron-right small"></i></a>
                    </div>
                  </div>
                </div>
                <!-- End Mega Menu Banner -->
              </div>
              <!-- End Mega Menu -->
            </li>
            <!-- End Pages -->

            <li class="nav-item">
              <!-- Search -->
              <button class="btn btn-ghost-secondary btn-sm btn-icon" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbarSearch" aria-controls="offcanvasNavbarSearch">
                <i class="bi-search"></i>
              </button>
              <!-- End Search -->

              <!-- Shopping Cart -->
              {% if user.is_authenticated %}
               <button type="button" onclick="emptyCart(this)" class="btn btn-ghost-secondary btn-sm btn-icon" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbarEmptyShoppingCart" aria-controls="offcanvasNavbarEmptyShoppingCart">
                <i class="bi-basket"></i>
              </button>
              {% endif %}
              <!-- End Shopping Cart -->
              {% if not user.is_authenticated %}
               <button class="btn btn-primary btn-transition" type="button" data-bs-toggle="modal"
                data-bs-target="#signupModal">Login</button>
              {% endif %}
              {% if user.is_authenticated %}
               <a href="" type="button" class="btn btn-ghost-secondary btn-md btn-icon">
                <i class="bi-person-circle"></i>
               </a>
              {% endif %}
            </li>
          </ul>
        </div>
        <!-- End Collapse -->
      </nav>
    </div>
  </header>

frontend/templates/frontend/widgets/intro.html
{% load static %}

<div class="border-bottom">
    <div class="container content-space-2">
        <div class="row">
            <div class="col-md-4 mb-7 mb-md-0">
                <!-- Icon Block -->
                <div class="d-flex">
                    <div class="flex-shrink-0">
                        <img class="avatar avatar-4x3" src="{% static 'frontend/images/oc-protected-card.svg' %}"
                            alt="Image Description">
                    </div>
                    <div class="flex-grow-1 ms-4">
                        <h4 class="mb-1">Secure checkout</h4>
                        <p class="small mb-0">Guaranteed safe checkout</p>
                    </div>
                </div>
                <!-- End Icon Block -->
            </div>
            <!-- End Col -->

            <div class="col-md-4 mb-7 mb-md-0">
                <!-- Icon Block -->
                <div class="d-flex">
                    <div class="flex-shrink-0">
                        <img class="avatar avatar-4x3" src="{% static 'frontend/images/oc-return.svg' %}"
                            alt="Image Description">
                    </div>
                    <div class="flex-grow-1 ms-4">
                        <h4 class="mb-1">30 Days return</h4>
                        <p class="small mb-0">We offer you a full refund within 30 days of purchase.</p>
                    </div>
                </div>
                <!-- End Icon Block -->
            </div>
            <!-- End Col -->

            <div class="col-md-4">
                <!-- Icon Block -->
                <div class="d-flex">
                    <div class="flex-shrink-0">
                        <img class="avatar avatar-4x3" src="{% static 'frontend/images/oc-truck.svg' %}"
                            alt="Image Description">
                    </div>
                    <div class="flex-grow-1 ms-4">
                        <h4 class="mb-1">Free shipping</h4>
                        <p class="small mb-0">Automatically receive free standard shipping on every order.</p>
                    </div>
                </div>
                <!-- End Icon Block -->
            </div>
            <!-- End Col -->
        </div>
        <!-- End Row -->
    </div>
</div>

frontend/templates/frontend/widgets/subscribe.html
{% load static %}

<div class="bg-light">
    <div class="container content-space-2">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
            <div class="row justify-content-lg-between">
                <!-- Heading -->
                <div class="mb-5">
                    <span class="text-cap">Subscribe</span>
                    <h2>Get the latest from Vang</h2>
                </div>
                <!-- End Heading -->

                <form>
                    <!-- Input Card -->
                    <div class="input-card input-card-pill input-card-sm border mb-3">
                        <div class="input-card-form">
                            <label for="subscribeForm" class="form-label visually-hidden">Enter email</label>
                            <input type="text" class="form-control form-control-lg" id="subscribeForm"
                                placeholder="Enter email" aria-label="Enter email">
                        </div>
                        <button type="button" class="btn btn-primary btn-lg rounded-pill">Subscribe</button>
                    </div>
                    <!-- End Input Card -->
                </form>

                <p class="small">You can unsubscribe at any time. Read our <a href="#">privacy policy</a></p>
            </div>
        </div>
    </div>
</div>